### PR TITLE
Configuration for automated tests on Travis

### PR DESCRIPTION
**Pull request by aviks**
Please enable testing of Datetime.jl via the travis dashboard.

### CODE REVIEW

**Comment by quinnj** [comment]
I'm guess the Travis failure will be fixed with the other commit I just merged?

**Comment by aviks** [comment]
Yes, that's the idea.

**Comment by aviks** [comment]
Tests now passing on travis https://travis-ci.org/aviks/Datetime.jl/builds/11384322

**Comment by quinnj** [comment]
Great! Thanks for doing this. I've been meaning to learn about the travis integration as I'm pretty clueless, but just haven't found the time.

**Comment by aviks** [comment]
NP. You'll need to log into Travis (with your github credentials) and enable travis builds for this project. (The link above is for my fork)

**Comment by quinnj** [comment]
Got it. It should be enabled now.

**Pull request merged**
